name: Add Patch Notes
on:
  pull_request:
    types: [closed]
jobs:
  parse:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base branch (${{ github.base_ref }})
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - run: npm install minimist semver-utils fs-extra
      - name: Checkout stoneG/add-patch-notes-action
        uses: actions/checkout@v2
        with:
          repository: stoneG/add-patch-notes-action
          ref: refs/heads/main
          path: ./.github/actions/add-patch-notes
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Parse patch note
        id: patchNotes
        uses: ./.github/actions/add-patch-notes
      - name: Write patch note
        run: npm run add-patch-note -- --baseRef=${{ github.base_ref }} --patchNote=${{ steps.patchNotes.output.patchNotes }}
      - name: Commit & push patch note
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(patchNotes): add patch notes"
          # Optional branch to push to, defaults to the current branch
          branch: ${{ github.base_ref }}

          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: patch-notes/json/*.json