name: Add Patch Notes
on:
  pull_request:
    types: [closed]
jobs:
  parse:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout base branch (${{ github.base_ref }})
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - run: npm install
      - name: Checkout stoneG/add-patch-notes-action
        uses: actions/checkout@v2
        with:
          repository: stoneG/add-patch-notes-action
          ref: refs/heads/main
          path: ./.github/actions/add-patch-notes
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Parse patch note
        id: patchNote
        uses: ./.github/actions/add-patch-notes

      - name: Print parsed patch note
        run: echo "Found patch note ${{ steps.patchNote.outputs.type }}(${{ steps.patchNote.outputs.context }}) - ${{ steps.patchNote.outputs.note }}"

      - name: Write patch note
        run: npm run add-patch-note -- --baseRef=${{ github.base_ref }} --type=${{ steps.patchNote.outputs.type }} --context=${{ steps.patchNote.outputs.context }} --note="${{ steps.patchNote.outputs.note }}"

      - name: Commit & push patch note
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(patchNotes): add patch note"
          # Optional branch to push to, defaults to the current branch
          branch: ${{ github.base_ref }}

          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: patch-notes/json/*.json