name: Build Patch Notes (Stable)
on:
  pull_request:
    types: [opened]
    branches:
      - release
  issue_comment:
    types: [created]
jobs:
  stable:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '!build-stable-patch-notes'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  beta:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '!build-beta-patch-notes'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          
  build:
    needs: [stable, beta]
    runs-on: ubuntu-latest
    if: needs.stable.outputs.triggered == 'true' || needs.beta.outputs.triggered == 'true'

    steps:
      - run: echo ${{ toJSON(github) }}
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.pull_request.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install minimist semver-utils fs-extra dateformat react react-dom @babel/core @babel/cli @babel/preset-react @babel/plugin-transform-runtime

      - name: Set stable patch notes release date
        if: needs.stable.outputs.triggered == 'true'
        run: npm run set-patch-notes-release-date -- --stable

      - name: Set beta patch notes release date
        if: needs.beta.outputs.triggered == 'true'
        run: npm run set-patch-notes-release-date -- --beta

      - name: Generate HTML patch notes
        run: npm run generate-html-patch-notes

      - name: Commit & push patch note
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(patchNotes): version patch notes to ${{ github.event.issue.pull_request.head_ref }}"
          branch: ${{ github.event.issue.pull_request.head_ref }}
          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: patch-notes/html/*.html