name: Patch Notes
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stoneG/add-patch-notes-action
        uses: actions/checkout@v2
        with:
          repository: stoneG/add-patch-notes-action
          ref: refs/heads/main
          path: ./.github/actions/add-patch-notes
      - name: Add patch notes
        uses: ./.github/actions/add-patch-notes
        id: patchNotes
      - name: Print patch note
        run: echo "Found patch note ${{ steps.patchNotes.outputs.type }}(${{ steps.patchNotes.outputs.context }}) - ${{ steps.patchNotes.outputs.patchNote }}"