name: Version Patch Notes
on:
  create:
jobs:
  version_main_patch_notes:
    # Only run this job if this is a vX.X.X named tag
    if: github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Set version environment variable
        id: version
        run: echo ::set-output name=version::$(echo ${{ github.event.ref }} | cut -c1 --complement)

      - name: Checkout release (${{ github.event.ref }})
        uses: actions/checkout@v2
        with:
          ref: release-candidate-${{ steps.environment.outputs.version }}

      - name: Version main patch notes
        run: sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.event.ref }}/' ./patch-notes/json/unreleased.json

      - name: Move main patch notes
        run: echo ${{ github.event.ref }} | cut -c1 --complement | xargs -I {} mv ./patch-notes/json/unreleased.json ./patch-notes/json/{}.json

      - name: Commit & push patch note
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(patchNotes): version patch notes to ${{ github.event.ref }}"
          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: patch-notes/json/*.json
  version_beta_patch_notes:
    # Only run this job if this is a vX.X.X named tag
    if: github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Set version environment variable
        id: version
        run: echo ::set-output name=version::$(echo ${{ github.event.ref }} | cut -c1 --complement)

      - name: Checkout release (${{ github.event.ref }})
        uses: actions/checkout@v2
        with:
          ref: release-candidate-${{ steps.environment.outputs.version }}

      - name: Version beta patch notes
        run: sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.event.ref }}/' ./patch-notes/json/unreleased-beta.json

      - name: Version beta patch notes
        run: echo ${{ github.event.ref }} | cut -c1 --complement | xargs -I {} mv ./patch-notes/json/unreleased-beta.json ./patch-notes/json/{}-b.json

      - name: Commit & push patch note
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(patchNotes): version patch notes to ${{ github.event.ref }}"
          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: patch-notes/json/*.json